version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ec2-user
